plugins {
    id "eclipse"
    id "idea"
    id "java-library"
    id "net.neoforged.gradle.userdev" version "7.1.38"
    id "me.modmuss50.mod-publish-plugin" version "2.0.0"
}

version = mod_version + "-neoforge-" + minecraft_suffix
group = maven_group
base.archivesName = mod_id

java.toolchain.languageVersion = JavaLanguageVersion.of(java_target)

println("Java: " + System.getProperty("java.version") + " JVM: " + System.getProperty("java.vm.version") + "(" + System.getProperty("java.vendor") + ") Arch: " + System.getProperty("os.arch"))

// Keep parameter names when compiling
compileJava.options.compilerArgs.add '-parameters'

repositories {
    flatDir { dirs "libs" }
    maven { url "https://www.cursemaven.com" }
    exclusiveContent {
        forRepository {
            maven { url = "https://api.modrinth.com/maven" }
        }
        filter { includeGroup "maven.modrinth" }
    }
    maven { url = "https://repo.spongepowered.org/maven" }
    maven { url = "https://maven.caffeinemc.net/releases" }
}

dependencies {
    // NeoForge
    implementation "net.neoforged:neoforge:${neoforge_version}"

    // ModernFix
//    runtimeOnly "curse.maven:modernfix-790626:6171686"
    // Sodium
    compileOnly "net.caffeinemc:sodium-neoforge-mod:0.9.0+mc26.2"
//    runtimeOnly "net.caffeinemc:sodium-neoforge:0.8.1+mc1.21.11"
    // Iris
//    runtimeOnly "maven.modrinth:iris:1.10.3+1.21.11-neoforge"

    // Just Enough Items
//    runtimeOnly "curse.maven:jei-238222:${just_enough_items_file}"
}

// Include resources generated by data generators.
sourceSets.main.resources { srcDir "src/generated/resources" }

tasks.withType(ProcessResources).configureEach {
    inputs.property "version", version

    // Replace the mod version
    Map<String, ?> copyProperties = project.properties.clone() as Map<String, ?>
    //noinspection UnnecessaryQualifiedReference
    var matcher = java.util.regex.Pattern.compile("[^.0-9]").matcher(copyProperties.mod_version as String)
    if (matcher.find())
        copyProperties.mod_version = copyProperties.mod_version.substring(0, matcher.start()) + "+" + copyProperties.mod_version.substring(matcher.start())

    filesMatching(["META-INF/neoforge.mods.toml", "modid.mixins.json", "pack.mcmeta"]) {
        expand copyProperties
    }

    exclude "**/*.pdn"

    rename "^modid.mixins.json\$", "${mod_id}.mixins.json"
    rename "^icon.png\$", "${mod_id}.png"
}

minecraft.accessTransformers.file rootProject.file("src/main/resources/META-INF/accesstransformer.cfg")

runs {
    configureEach {
        systemProperty "forge.logging.markers", "REGISTRIES"

        //noinspection GroovyAssignabilityCheck
        modSource sourceSets.main
    }

    client {
    }

    server {
        argument "-nogui"
    }

    clientData {
        //noinspection GroovyAssignabilityCheck
        arguments "--mod", mod_id
        arguments "--all"
        arguments "--output", file("src/generated/resources/").getAbsolutePath()
        arguments "--existing", file("src/main/resources").getAbsolutePath()
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

publishMods {
    file = jar.archiveFile
    displayName = "${mod_name} ${mod_version} for NeoForge ${minecraft_suffix.substring(2)}"
    version = project.version
    //noinspection UnnecessaryQualifiedReference
    type = me.modmuss50.mpp.ReleaseType.of(publishing_release_type.toUpperCase())
    changelog = file("changelog.md").text
    modLoaders.add("neoforge")
    maxRetries = 2

    curseforge {
        accessToken = System.getenv("CURSEFORGE_TOKEN")
        projectId = curseforge_project_id
        if (!curseforge_required_dependency_ids.isEmpty())
            curseforge_required_dependency_ids.split(" ").each it::requires
        if (!curseforge_optional_dependency_ids.isEmpty())
            curseforge_optional_dependency_ids.split(" ").each it::optional
        publishing_game_versions.split(" ").each minecraftVersions::add
        clientRequired = true
        serverRequired = true
    }

    modrinth {
        accessToken = System.getenv("MODRINTH_TOKEN")
        projectId = modrinth_project_id
        displayName = "${mod_name} ${mod_version}"
        if (!modrinth_required_dependency_ids.isEmpty())
            modrinth_required_dependency_ids.split(" ").each it::requires
        if (!modrinth_optional_dependency_ids.isEmpty())
            modrinth_optional_dependency_ids.split(" ").each it::optional
        publishing_game_versions.split(" ").each minecraftVersions::add
    }
}

// Rename the 'publishMods' task
tasks.publishMods.group = "other"
tasks.register("publishAll") {
    group = "publishing"
    dependsOn(tasks.publishMods)
}
