# Gradle settings
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.21.3
minecraft_dependency=[1.21.2,1.21.4)
minecraft_suffix=mc1.21.3
java_target=21
java_dependency=>=21
resource_pack_format=57

# NeoForge
neoforge_version=21.3.58
neoforge_dependency=[21.3.58,)
javafml_dependency=[1,)

# Mixin
mixin_minimum_version=0.8
mixin_package=mixin
mixin_compatibility_level=JAVA_17
mixin_plugin=FusionMixinPlugin

# Mod properties
mod_name=Fusion
mod_description=Fusion allows resource packs to use additional texture and model types such as connected textures!
mod_id=fusion
mod_version=1.3.0
mod_license=All rights reserved
mod_page=https://www.curseforge.com/minecraft/mc-mods/fusion-connected-textures
mod_sources=https://github.com/SuperMartijn642/Fusion
mod_issues=https://github.com/SuperMartijn642/Fusion/issues
mod_package=com.supermartijn642.fusion
mod_main_class=Fusion
maven_group=com.supermartijn642

# Publishing
publishing_release_type=stable
publishing_game_versions=1.21.2 1.21.3
curseforge_project_id=854949
curseforge_required_dependency_ids=
curseforge_optional_dependency_ids=
modrinth_project_id=p19vrgc2
modrinth_required_dependency_ids=
modrinth_optional_dependency_ids=

# Runtime mods
just_enough_items_file=5630564
